name: Deno with Docker

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest
        env:
            MONGOOSE_CONNECT_URI: ${{ secrets.MONGOOSE_CONNECT_URI }}
            JWT_SECRET: "hashjasiouibkbndmnbjioeiuo899r3783hg"
            IMAP_USERNAME: ${{ secrets.IMAP_USERNAME }}
            IMAP_PASSWORD: ${{ secrets.IMAP_PASSWORD }}
        steps:
            - name: Setup repo
              uses: actions/checkout@v3

            - name: Setup Deno
              uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31 # v1.1.2
              with:
                  deno-version: v1.x

            - name: Run tests
              run: deno test -A

    build:
        needs: test
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        steps:
            - name: Setup repo
              uses: actions/checkout@v3

            - name: Build Docker image
              run: docker build . -t willebergh/mega-api:dev

            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Push Docker image
              run: docker push willebergh/mega-api:dev

    deploy:
        needs: build
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        steps:
            - name: Update server
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.CD_SERVER_HOST }}
                  username: ${{ secrets.CD_SERVER_USERNAME }}
                  password: ${{ secrets.CD_SERVER_PASSWORD }}
                  script: ~/mega/update_api.sh
